### ISSUE TITLE
Updating to 0.3.0: error: linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by mikbry** [ralfbiedert/openh264-rust#24]
- I made a simple project based on the code from FrankenApps here:
https://users.rust-lang.org/t/create-mp4-video-from-pictures-in-rust/70850
- I added latest dependencies, not versions referenced in the post. So I use openh264 version 0.3.0 instead of 0.2.11
I changed the code to use `openh264::formats::YUVBuffer::with_rgb`instead of `openh264::formats::RBGYUVConverter::new`.

I got `error: linking with `cc` failed: exit status: 1`
And a list of undefined symbols:
```
= note: Undefined symbols for architecture x86_64:
            "_AnalysisVaaInfoIntra_sse2", referenced from:
                WelsEnc::InitIntraAnalysisVaaInfo(WelsEnc::TagWelsFuncPointerList*, unsigned int) in libopenh264_sys2-62705b02f590407b.rlib(md.o)
            "_AnalysisVaaInfoIntra_ssse3", referenced from:
                WelsEnc::InitIntraAnalysisVaaInfo(WelsEnc::TagWelsFuncPointerList*, unsigned int) in libopenh264_sys2-62705b02f590407b.rlib(md.o)
            "_BilateralLumaFilter8_sse2", referenced from:
                WelsVP::CDenoiser::InitDenoiseFunc(WelsVP::TagDenoiseFuncs&, int) in libopenh264_sys2-62705b02f590407b.rlib(denoise.o)
            "_CavlcParamCal_sse42", referenced from:
                WelsEnc::InitCoeffFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int, int) in libopenh264_sys2-62705b02f590407b.rlib(set_mb_syn_cavlc.o)
            "_DeblockChromaEq4H_ssse3", referenced from:
                WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int) in libopenh264_sys2-62705b02f590407b.rlib(deblocking.o)
            "_DeblockChromaEq4V_ssse3", referenced from:
                WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int) in libopenh264_sys2-62705b02f590407b.rlib(deblocking.o)
            "_DeblockChromaLt4H_ssse3", referenced from:
                WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int) in libopenh264_sys2-62705b02f590407b.rlib(deblocking.o)
            "_DeblockChromaLt4V_ssse3", referenced from:
                WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int) in libopenh264_sys2-62705b02f590407b.rlib(deblocking.o)
            "_DeblockLumaEq4V_ssse3", referenced from:
                WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int) in libopenh264_sys2-62705b02f590407b.rlib(deblocking.o)
                _DeblockLumaEq4H_ssse3 in libopenh264_sys2-62705b02f590407b.rlib(deblocking_common.o)
            "_DeblockLumaLt4V_ssse3", referenced from:
                WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int) in libopenh264_sys2-62705b02f590407b.rlib(deblocking.o)
                _DeblockLumaLt4H_ssse3 in libopenh264_sys2-62705b02f590407b.rlib(deblocking_common.o)
```

If I use `0.2.18` and revert back YUV changes, all is building and running fine.

I am on Macos Ventura x64

**Comment by ralfbiedert** [comment]
Thanks for the report. My guess is this is related to the `openh264-sys2/build.rs` changes I made to clean things up, which must have caused some issues (likely around `try_compile_nasm()`). 

I don't have a Mac anymore and would greatly appreciate if you or someone could help debugging this.

**Comment by gil0mendes** [comment]
It seems like it was working before because `nasm` was not being used at all.

Before there was a flag `#[cfg(feature = "asm")]`, if the `asm` was not defined nasm would not be used. In the other hand, now, the code inside `try_compile_nasm` is always executed.

This can be proved by removing the contents of the `try_compile_nasm` function.
```
fn try_compile_nasm(cc_build: &mut Build, root: &str) {}
```

Now, when we run the cargo command, it will be linked with no problem.

**Comment by ralfbiedert** [comment]
Thanks! Do you have `nasm` installed on MacOS? Like, is only the detection broken, or is this related to some bad flags?

**Comment by gil0mendes** [comment]
In reality there is something really wild going on because I was able to compile it just fine yesterday, the problem only started today; that is the reason why I found this GitHub issue 😅

I don't recall change anything since yesterday on my environment. I have nasm version `2.15.05` installed, and seems like the `build.rs` is detecting it correctly.

Another thing that I did, was to copy the function code from a [previous state](https://github.com/ralfbiedert/openh264-rust/blob/558f2e996b857d684b253556e8394e0e6f32e82f/openh264-sys2/build.rs), without the `#[cfg(feature = "asm")]` condition and the result is the same.

Any hint on you better debug what is happening, I'm running out of ideas 😬

**Comment by ralfbiedert** [comment]
What OS / Rust version do you use?

**Comment by gil0mendes** [comment]
OS: `macOS 12.6.1`
Rust: `1.67.0-nightly`, but already tested with stable `1.61.0`

**Comment by gil0mendes** [comment]
Also, if I look for the supposed missing symbols on the library they are there 🤔

```
nm /Users/gil0mendes/projects/ghost-screen/openh264/target/debug/deps/libopenh264_sys2-ba9a72295344cf6d.rlib | grep DeblockChromaEq4H_ssse3
/Users/gil0mendes/projects/ghost-screen/openh264/target/debug/deps/libopenh264_sys2-ba9a72295344cf6d.rlib:lib.rmeta: no symbols
00000000000009d0 T DeblockChromaEq4H_ssse3
                 U _DeblockChromaEq4H_ssse3
                 U _DeblockChromaEq4H_ssse3
```

**Comment by gil0mendes** [comment]
I just opened a PR with a possible fix to this issue. Happy to apply any change or suggestion to enhance it 😊

**Comment by ralfbiedert** [comment]
0.3.1 is out which hopefully fixes this, thanks @gil0mendes. Please comment or reopen if it doesn't.

**Comment by gil0mendes** [comment]
No problem, was a pleasure to contribute 😊

@mikbry if you have the time just to confirm if this fixes it for you too would be wonderful, tks 🤗

**Comment by mikbry** [comment]
Thanks @gil0mendes @ralfbiedert , 0.3.1 fixes the prb !
